modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/kyleplo/fated-inventory/issues"
license = "LGPL-3.0"

[[mods]]
modId = "fated_inventory"
version = "${version}"
displayName = "Fated Inventory"
authors = "kyleplo"
description = '''
A unique take on preserving the inventory on death
'''
logoFile = "src/main/resources/assets/fated_inventory/icon.png"

[[dependencies.fated_inventory]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fated_inventory]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"